[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
regex = "1"
once_cell = "1.16.0"

[profile.dev]
opt-level = 3
debug = true
